name: Lint and Test
on:
  push:
  pull_request:
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
      - name: lint
        run: make lint
      - name: test
        run: make test
